#!/bin/bash

echo Building the project .. 
npm run build

echo Copy important files ..

cp Dockerfile build

cp package.json build

echo Navigate into build directory .. 
 




echo Create new image ..
echo docker build -t birkirfb/tictactoe .
docker build -t birkirfb/tictactoe .


echo docker push birkirfb/tictactoe

echo "Done"

