version: '2'
services:
  server:
    environment:
      - 'PORT=3000' #the port the server is runned on.
      - 'NODE_ENV=production' #environment being runned
    image: 'birkirfb/tictactoe:${GIT_COMMIT}' #the name of the image the server is on.
    ports:
      - '3000:3000' #local port
      - '80:3000'
    links:
      - 'postgres' #the container which is going to be runned at the same time.
  postgres:
    environment:
      - 'POSTGRES_PASSWORD=mysecretpassword' #ENV variable for the postgres server.
    image: postgres #the name of the image the postgres server is on.
    ports: 
      - '5432:5432' #the port the postgres server is runned on.