version: '2'
services:
  server:
    environment:
      - 'NODE_ENV=development'
      - 'PORT=3000'
    image: 'birkirfb/tictactoe'
    build:
      context: '.'
      dockerfile: 'Dockerfile'
    ports:
      - '3000:3000'
    links:
      - 'postgres'
  postgres:
    environment:
      - 'POSTGRES_PASSWORD=mysecretpassword'
    image: postgres
    ports: 
      - '5432:5432'